[package]
name = "pseudochef"
version = "0.3.0"
edition = "2024"
license = "MIT"

[dependencies]
repak = { git = "https://github.com/trumank/repak", version = "0.2.3" }
shalrath = "0.2.6"
unreal_asset = { git = "https://github.com/astrotechies/unrealmodding", rev = "79c6f34" }
ordered-float = "3.9.2"  # should match version used by unreal_asset
pseudocooker = { path = "pseudocooker" }
glam = "0.33.2"
itertools = "0.15.0"
spade = "2.15.1"
humansize = "2.1.3"
humantime = "2.4.0"
