#[derive(Default)]
pub struct UpgradeData {
    pub id: i32,
    pub display_name: String,
    pub powerup_tier: i32,
    pub instructions: String,
    pub description: String,
    pub extended_description: String,
    pub display_image: String,
}

pub fn get_upgrade_data(key: &str) -> UpgradeData {
    // Extracted from DT_UpgradeData via examples/dump_datatable.rs. The
    // table's Model reference is null for every row, so it isn't represented
    // here. display_image is the Texture2D object name the row references,
    // found under /Game/MatTex/Textures/UI/icons/ in the data table's imports;
    // empty when the row has none. Rows with multiple ExtendedDescription
    // entries are joined with a blank line.
    let ud = |id: i32,
              display_name: &str,
              powerup_tier: i32,
              instructions: &str,
              description: &str,
              extended_description: &str,
              display_image: &str| {
        UpgradeData {
            id,
            display_name: display_name.to_string(),
            powerup_tier,
            instructions: instructions.to_string(),
            description: description.to_string(),
            extended_description: extended_description.to_string(),
            display_image: display_image.to_string(),
        }
    };
    match key {
        "attack" => ud(
            0,
            "Dream Breaker",
            0,
            "Press X Button/Left Click",
            "Attack freely while moving to vanquish foes.. Hiting enemies will build up magical power.\r\n\r\nTo use it, hold B Button/F Key to heal.",
            "Sybil will automatically hit whoever is closest, though you can also Lock-On with RB/Right Click.\r\n\r\nYour weapon can be dropped, or thrown with LB/tab. If you ever lose it, you can recall it at a save point by holding down the heal button.",
            "icon_attack",
        ),
        "airKick" => ud(
            1,
            "Sun Greaves",
            0,
            "Press A Button/Space bar while in the air.",
            "After a short delay, do an air kick. Hitting walls and objects with it will cause you to jump away. Can be done up to 3 times until reset.\r\n\r\nTry kicking early to maximize distance!",
            "The angle you come off of a wall is a reflection of the angle you are facing when you make contact. Don't try to push away from the wall until you bounce! \r\n\r\nIf the angle is close to perpendicular, your jump will be higher but send you less far.\r\n\r\nTry to kick so that your foot hits the wall, not your body, for maxium distance. \r\n\r\nYou can even kick quite early, so long as you touch the wall before the action ends.\r\n\r\nTiming, spacing, and angle are all important!",
            "icon_greaves",
        ),
        "slide" => ud(
            2,
            "Slide",
            0,
            "Press Left Trigger/Q Key on the ground to Slide.",
            "Gain a boost of speed, and slide under tight gaps and some attacks. \r\nBut by itself, an incomplete technique.",
            "",
            "icon_slide",
        ),
        "plunge" => ud(
            3,
            "Sunsetter",
            0,
            "Press LT/Q key while in the air to Plunge downwards, which can then chain into a High Jump.",
            "Use this to break through fragile floors or simply stop yourself in the air. \r\n\r\nJumping right after the Plunge will result in a High Jump.",
            "You can jump right after you start up the plunging action, which will cancel it into a backflip.\r\n\r\nThis can only be done once until reset, so be careful!",
            "icon_plunge",
        ),
        "wallRide" => ud(
            4,
            "Cling Gem",
            0,
            "Press RT/Left Shift while falling along walls to Ride them",
            "Hold tight to walls while you propel yourself a short distance. Can be jumped out of, and can go around curved walls and corners.",
            "You can Wall Ride 6 times until reset.\r\n\r\nActivation is easier when you move along walls, not directly into them.",
            "icon_clingGem",
        ),
        "light" => ud(
            5,
            "Ascendant Light",
            0,
            "Attack objects and enemies to bounce off of them.",
            "In addition, your weapon now glows brightly, even in the darkest of places. ",
            "",
            "icon_Light",
        ),
        "projectile" => ud(
            6,
            "Soul Cutter",
            0,
            "Hold Attack until your weapon is ready, release to fire",
            "Enhances your charge attack with a long distance projectile. \r\nIf you have power available, it will consume a level to enhance the damage.\r\n\r\nCan be aimed in first person, if need be.",
            "",
            "icon_Projectile",
        ),
        "sprint" => ud(7, "Haste", 0, "", "debug option", "", ""),
        "powerBoost" => ud(
            8,
            "Indignation",
            0,
            "Higher Power gives you increased combat capabilities.",
            "Upon reaching power level 2, the range of your attack is extended. \r\nAt level 3, your damage is increased. \r\n\r\nThis is reset upon spending it on a heal.",
            "",
            "icon_indignationEye",
        ),
        "SlideJump" => ud(
            9,
            "Solar Wind",
            0,
            "Jump while Sliding.",
            "Completes the technique of the slide. Cross long distances with a airy long jump. ",
            "",
            "icon_slideJump",
        ),
        "guard" => ud(10, "Defender", 0, "Press Y Button/Ctrl", "debug option", "", ""),
        "chargeAttack" => ud(
            11,
            "Strikebreak",
            0,
            "Hold Attack until your weapon is ready, release to strike.",
            "A more powerful attack that locks you in place. Can be used to destroy heavy barriers.",
            "",
            "icon_chargeAttack",
        ),
        "map" => ud(
            12,
            "Memento",
            0,
            "Press D-Pad Up/Tab to see your mental map",
            "To move the map, press LockOn + Move Camera while active.\r\n\r\nRooms will be revealed to you as you enter them, allowing you to more easily chart a course through an area.",
            "",
            "",
        ),
        "extraKick" => ud(
            20,
            "Heliiacal Power",
            1,
            "Allows you to preform an additional air kick",
            "",
            "",
            "icon_HeliacalPower",
        ),
        "damageBoost" => ud(
            21,
            "Martial Prowess",
            1,
            "Increases Damage dealt",
            "",
            "",
            "icon_martialProwress",
        ),
        "magicPiece" => ud(
            22,
            "Clear Mind",
            1,
            "Collect all 3 to hold more magical power",
            "",
            "",
            "icon_clearMind",
        ),
        "magicHaste" => ud(
            23,
            "Empathy",
            1,
            "Bonus Power is built from attacks.",
            "",
            "",
            "icon_Empathy",
        ),
        "HealBoost" => ud(
            24,
            "Good Graces",
            1,
            "Increases healing power by 1/2 pip",
            "",
            "",
            "icon_graces",
        ),
        "airRecovery" => ud(
            25,
            "Aerial Finesse",
            1,
            "Press Jump during your knockback state to regain balance.",
            "",
            "",
            "icon_recovery",
        ),
        "mobileHeal" => ud(
            26,
            "Pilgrimage",
            1,
            "You can move slowly while channeling a Heal",
            "",
            "",
            "icon_pilgrimage",
        ),
        "healthPiece" => ud(
            27,
            "Heavenly Body",
            1,
            "Will increase your maximum health",
            "",
            "",
            "",
        ),
        "outfitPro" => ud(30, "Professionalism", 1, "Gained a new outfit!", "", "", ""),
        "outfitShoujo" => ud(31, "a Guardian", 1, "Gained a new outfit!", "", "", ""),
        "outfitKnight" => ud(32, "Chivalry", 1, "Gained a new outfit!", "", "", ""),
        "outfitPast" => ud(33, "a Bleeding Heart", 1, "Gained a new outfit!", "", "", ""),
        "outfitJam" => ud(34, "Nostalgia ", 1, "Gained a new outfit!", "", "", ""),
        "outfitFaith" => ud(35, "Devotion", 1, "Gained a new outfit!", "", "", ""),
        "outfitClassy" => ud(36, "Class", 1, "Gained a new outfit!", "", "", ""),
        "outfitSweater" => ud(37, "Sweater", 1, "Gained a new outfit!", "", "", ""),
        _ => UpgradeData::default(),
    }
}
