name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write  # Allow action to create releases.
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: scripts/windows/make_release_zip.bat
      - name: Release (Windows)
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v3
        with:
          files: pseudochef-*-*-*.zip

      - name: Package (${{ runner.os }})
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: scripts/posix/make_release_tarball.sh
      - name: Release (${{ runner.os }})
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: softprops/action-gh-release@v3
        with:
          files: pseudochef-*-*-*.tar.gz
